version: '1.0'

services:
  db:
    image: mysql:8.0.32
    container_name: veterinary
    restart: always
    volumes:
      - ./db/sql/veterinary/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/veterinary/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_DATABASE: veterinary
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306